still testing source implementation other than root

diff --git a/snapshot-z b/snapshot-z
--- a/snapshot-z
+++ b/snapshot-z
@@ -1,4 +1,5 @@
 #!/bin/bash
+set -euo pipefail
 
 if [[ $EUID -ne 0 && -z ${TESTING_SKIP_ROOT_CHECK} ]]; then
    echo "This script must be run as root"
@@ -39,7 +40,7 @@ SKIP_UPDATE=false
 SOURCE_DIR="/"
 
 print_usage() {
-  echo "usage: $0 [-p] [-e folder_to_exclude] [-d] [-u] snapshot_name"
+  echo "usage: $0 [-p] [-e folder_to_exclude] [-d] [-u] [-s source_dir] snapshot_name"
   echo "Optional arguments:"
   echo ""
   echo "  -h        Print this help message"
@@ -48,6 +49,7 @@ print_usage() {
   echo "  -y        Answer 'yes' to all prompts"
   echo "  -d        Dry run prints each step instead of running snapshot script"
   echo "  -u        Skip the automatic self-update check"
+  echo "  -s        Specify any path other than root for snapshoting"
   echo ""
   echo " cc-snapshot version 0.2.0"
 }
@@ -77,11 +79,11 @@ check_size(){
 # Reassign filtered args to $@
 #set -- "${NEW_ARGS[@]:-}"
 
-while getopts "hpe:fydus" opt; do
+while getopts "hpe:fydus:" opt; do
   case $opt in
 
     s)
-      SOURCE_DIR="$OPTRG"
+      SOURCE_DIR="$OPTARG"
       ;;
     h)
       print_usage
@@ -111,7 +113,23 @@ while getopts "hpe:fydus" opt; do
 done
 
 shift $((OPTIND - 1)) 
+SNAPSHOT_NAME="${1:-$(hostname)_$(uuidgen)}"
 SOURCE_DIR="${SOURCE_DIR:-/}"
+
+if [[ ! -d "$SOURCE_DIR" ]]; then
+  echo "ERROR: Specified source directory '$SOURCE_DIR' does not exist."
+  exit 1
+fi
+
+if [[ "$SOURCE_DIR" != /* ]]; then
+  echo "ERROR: Source directory must be an absolute path."
+  exit 1
+fi
+
+echo "Snapshotting from directory: $SOURCE_DIR"
+
+echo "Creating snapshot named '$SNAPSHOT_NAME'"
+
 #####Testing functions using dummy stage 
 
 if [[ -n "${DUMMY_STAGE:-}" ]]; then
@@ -202,10 +220,10 @@ if [ -f "$PROVENANCE_FILE" ]; then
 fi
 ###### Get provenance properties end ######
 
-set -eu
-set -o pipefail
+#set -eu
+#set -o pipefail
 
-shift $((OPTIND-1))
+#shift $((OPTIND-1))
 
 HOSTNAME=$(hostname)
 UUID=$(uuidgen)
@@ -245,6 +263,14 @@ cat >$EXCLUDE_FROM <<EOF
 # User excludes
 $(printf "%s\n" "${EXCLUDE_FOLDERS[@]:-}")
 EOF
+
+# Tar the specified source directory
+if [[ "$DRY_RUN" == true ]]; then
+  echo "[DRY_RUN] Would run: tar -czf /tmp/$SNAPSHOT_NAME.tar.gz -X $EXCLUDE_FROM -C $SOURCE_DIR ."
+else
+  tar -czf "/tmp/$SNAPSHOT_NAME.tar.gz" -X "$EXCLUDE_FROM" -C "$SOURCE_DIR" .
+  echo "Snapshot created at /tmp/$SNAPSHOT_NAME.tar.gz"
+fi
 
 DISTRO=$(gawk -F= '/^NAME/{print $2}' /etc/os-release | tr -d \"\' | tr ' ' '-')
 UBUNTU='Ubuntu'
@@ -297,10 +323,10 @@ else
   OS_AUTH_URL=$(extract_json_key "auth_url_v3" "$JSON_VENDOR_DATA")
 fi
 
-if run_cmd "dmesg | grep -q Hypervisor"; then
+if dmesg | grep -q Hypervisor; then
   # The current instance is apparently not a baremetal node.
-  >&2 run_cmd echo "Error: cc-snapshot is only supported for baremetal instances."
-  run_cmd exit 1
+  >&2 echo "Error: cc-snapshot is only supported for baremetal instances."
+  exit 1
 fi
 
 export OS_REGION_NAME=$REGION
@@ -352,7 +378,7 @@ prepare_tarball(){
   until [ $n -ge 5 ]
   do
     #run_cmd tar --create --file $CC_SNAPSHOT_TAR_PATH ${TAR_ARGS[@]} / && break
-    run_cmd tar --create --file "$CC_SNAPSHOT_TAR_PATH" "${TAR_ARGS[@]}" "$SOURCE_DIR" && break    
+    run_cmd tar --create --file "$CC_SNAPSHOT_TAR_PATH" "${TAR_ARGS[@]}" -C "$SOURCE_DIR" . && break    
     n=$[$n+1]
     sleep 15
   done
@@ -458,17 +484,33 @@ create_disk_image(){
 #  total_disk_size=$(($filesystem_size + 1500))
 
   # 550M for UEFI partition and 8M for BIOS partition
-  run_cmd guestfish -N $CC_SNAPSHOT_CONVERTED_PATH=disk:"$total_disk_size"M -- \
-  part-init /dev/sda gpt : \
-  part-add /dev/sda primary 2048 1128447 : \
-  part-add /dev/sda primary 1128448 1144831 : \
-  part-add /dev/sda primary 1144832 -40 : \
-  mkfs $FS /dev/sda3 label:$LABEL : \
-  mkfs vfat /dev/sda1 label:MKFS_ESP : \
-  mount /dev/sda3 / : tar-in $CC_SNAPSHOT_TAR_PATH / : mount /dev/sda1 /boot/efi : \
-  sh "parted /dev/sda set 2 bios_grub on" : \
-  sh "parted /dev/sda set 1 esp on || true" : \
-  sh "$GRUBNAME $extra_options && $GRUB_MKCONFIG -o $GRUB_CFG $EXTRA_CMD"
+  #run_cmd guestfish -N $CC_SNAPSHOT_CONVERTED_PATH=disk:"$total_disk_size"M -- \
+  #part-init /dev/sda gpt : \
+  #part-add /dev/sda primary 2048 1128447 : \
+  #part-add /dev/sda primary 1128448 1144831 : \
+  #part-add /dev/sda primary 1144832 -40 : \
+  #mkfs $FS /dev/sda3 label:$LABEL : \
+  #mkfs vfat /dev/sda1 label:MKFS_ESP : \
+  #mount /dev/sda3 / : tar-in $CC_SNAPSHOT_TAR_PATH / : mount /dev/sda1 /boot/efi : \
+  #sh "parted /dev/sda set 2 bios_grub on" : \
+  #sh "parted /dev/sda set 1 esp on || true" : \
+  #sh "$GRUBNAME $extra_options && $GRUB_MKCONFIG -o $GRUB_CFG $EXTRA_CMD"
+  
+  # 550M for UEFI partition and 8M for BIOS partition
+run_cmd guestfish -N "$CC_SNAPSHOT_CONVERTED_PATH=disk:${total_disk_size}M" -- \
+  part-init /dev/sda gpt \
+  : part-add /dev/sda primary 2048 1128447 \
+  : part-add /dev/sda primary 1128448 1144831 \
+  : part-add /dev/sda primary 1144832 -40 \
+  : mkfs "$FS" /dev/sda3 label:"$LABEL" \
+  : mkfs vfat /dev/sda1 label:MKFS_ESP \
+  : mount /dev/sda3 / \
+  : sh "mkdir -p /boot/efi" \
+  : tar-in "$CC_SNAPSHOT_TAR_PATH" / \
+  : mount /dev/sda1 /boot/efi \
+  : sh "parted /dev/sda set 2 bios_grub on" \
+  : sh "parted /dev/sda set 1 esp on || true" \
+  : sh "$GRUBNAME $extra_options && $GRUB_MKCONFIG -o $GRUB_CFG $EXTRA_CMD"
 
 
   # To remove unwanted configuration information from your image, run:
